module "gke" {
  source                               = "../../../../modules/gke"
  project_id                           = var.project_id
  name                                 = var.cluster_name
  regional                             = var.is_regional
  region                               = var.region
  network                              = var.network
  network_project_id                   = var.network_project_id
  subnetwork                           = var.subnetwork
  master_ipv4_cidr_block               = var.master_ipv4_cidr_block // Optional
  ip_range_pods                        = var.ip_range_pods
  ip_range_services                    = var.ip_range_services
  create_service_account               = var.create_service_account
  service_account                      = var.service_account
  cluster_autoscaling                  = var.cluster_autoscaling
  enable_private_endpoint              = var.enable_private_endpoint
  enable_private_nodes                 = var.enable_private_nodes
  dns_allow_external_traffic           = var.enable_dns_endpoint
  enable_secret_manager_addon          = var.enable_secret_manager_addon
  default_max_pods_per_node            = var.default_max_pods_per_node
  remove_default_node_pool             = var.remove_default_node_pool
  enable_binary_authorization          = var.enable_binary_authorization
  deletion_protection                  = var.deletion_protection
  gateway_api_channel                  = var.gateway_api_channel // Accepted values are `CHANNEL_STANDARD` (this will enable the API) and `CHANNEL_DISABLED` (this will disable the API)
  identity_namespace                   = var.identity_namespace  // Default value of `enabled` automatically sets project-based pool `[project_id].svc.id.goog`
  enable_cost_allocation               = var.enable_cost_allocation
  security_posture_vulnerability_mode  = var.security_posture_vulnerability_mode
  security_posture_mode                = var.security_posture_mode
  release_channel                      = var.release_channel
  maintenance_start_time               = var.maintenance_start_time
  maintenance_end_time                 = var.maintenance_end_time
  maintenance_recurrence               = var.maintenance_recurrence
  node_pools                           = var.node_pools
  node_pools_labels                    = var.node_pools_labels
  disable_legacy_metadata_endpoints    = var.disable_legacy_metadata_endpoints
  logging_service                      = var.logging_service
  monitoring_enable_managed_prometheus = var.monitoring_enable_managed_prometheus
}
